USE polito;

-- ------------------------------------------------------------
-- ↓ degree table ↓
-- ------------------------------------------------------------
INSERT INTO
    degree (id, description)
VALUES
    (
        "32-1",
        "Laurea Triennale - INGEGNERIA DELL'AUTOVEICOLO"
    ),
    (
        "32-2",
        "Laurea Magistrale - AUTOMOTIVE ENGINEERING (INGEGNERIA DELL'AUTOVEICOLO)"
    ),
    (
        "32-6",
        "Laurea Triennale - INGEGNERIA DEI MATERIALI"
    ),
    (
        "32-9",
        "Laurea Triennale - INGEGNERIA ELETTRICA"
    ),
    (
        "32-11",
        "Laurea Triennale - INGEGNERIA AEROSPAZIALE"
    ),
    (
        "32-12",
        "Laurea Triennale - INGEGNERIA BIOMEDICA"
    ),
    (
        "32-13",
        "Laurea Triennale - INGEGNERIA CHIMICA E ALIMENTARE"
    ),
    ("32-14", "Laurea Triennale - INGEGNERIA CIVILE"),
    ("32-17", "Laurea Triennale - INGEGNERIA EDILE"),
    (
        "32-18",
        "Laurea Triennale - INGEGNERIA ENERGETICA"
    ),
    (
        "32-19",
        "Laurea Triennale - INGEGNERIA MECCANICA"
    ),
    -- ("32-21", "Laurea Triennale - INGEGNERIA MECCANICA"),
    (
        "32-22",
        "Laurea Triennale - INGEGNERIA PER L'AMBIENTE E IL TERRITORIO"
    ),
    (
        "32-23",
        "Laurea Triennale - MATEMATICA PER L'INGEGNERIA"
    ),
    (
        "32-26",
        "Laurea Magistrale - INGEGNERIA AEROSPAZIALE"
    ),
    (
        "32-27",
        "Laurea Magistrale - INGEGNERIA DELLA PRODUZIONE INDUSTRIALE E DELL'INNOVAZIONE TECNOLOGICA"
    ),
    (
        "32-28",
        "Laurea Magistrale - INGEGNERIA BIOMEDICA"
    ),
    (
        "32-29",
        "Laurea Magistrale - INGEGNERIA CHIMICA E DEI PROCESSI SOSTENIBILI"
    ),
    (
        "32-30",
        "Laurea Magistrale - INGEGNERIA CIVILE"
    ),
    (
        "32-34",
        "Laurea Magistrale - INGEGNERIA EDILE"
    ),
    (
        "32-35",
        "Laurea Magistrale - INGEGNERIA ELETTRICA"
    ),
    (
        "32-36",
        "Laurea Magistrale - INGEGNERIA ENERGETICA E NUCLEARE"
    ),
    (
        "32-37",
        "Laurea Magistrale - INGEGNERIA MECCANICA"
    ),
    (
        "32-38",
        "Laurea Magistrale - INGEGNERIA PER L'AMBIENTE E IL TERRITORIO"
    ),
    (
        "32-39",
        "Laurea Magistrale - INGEGNERIA MATEMATICA"
    ),
    (
        "32-42",
        "Laurea Triennale - INGEGNERIA DELLA PRODUZIONE INDUSTRIALE"
    ),
    -- ("32-44", "Laurea Triennale - INGEGNERIA DELLA PRODUZIONE INDUSTRIALE"),
    -- ("32-51", "Laurea Triennale - INGEGNERIA DELLA PRODUZIONE INDUSTRIALE"),
    -- ("32-52", "Laurea Triennale - INGEGNERIA DELL'AUTOVEICOLO"),
    -- ("32-53", "Laurea Magistrale - INGEGNERIA MECCANICA"),
    (
        "37-1",
        "Laurea Triennale - INGEGNERIA ELETTRONICA"
    ),
    (
        "37-3",
        "Laurea Triennale - INGEGNERIA INFORMATICA"
    ),
    (
        "37-9",
        "Laurea Triennale - INGEGNERIA FISICA"
    ),
    -- ("37-10", "Laurea Triennale - INGEGNERIA INFORMATICA"),
    (
        "37-13",
        "Laurea Magistrale - INGEGNERIA ELETTRONICA (ELECTRONIC ENGINEERING)"
    ),
    (
        "37-17",
        "Laurea Triennale - ELECTRONIC AND COMMUNICATIONS ENGINEERING (INGEGNERIA ELETTRONICA E DELLE COMUNICAZIONI)"
    ),
    (
        "37-18",
        "Laurea Magistrale - INGEGNERIA INFORMATICA (COMPUTER ENGINEERING)"
    ),
    (
        "37-20",
        "Laurea Magistrale - ICT FOR SMART SOCIETIES (ICT PER LA SOCIETA' DEL FUTURO)"
    ),
    (
        "37-21",
        "Laurea Triennale - INGEGNERIA DEL CINEMA E DEI MEZZI DI COMUNICAZIONE"
    ),
    (
        "37-22",
        "Laurea Magistrale - INGEGNERIA DEL CINEMA E DEI MEZZI DI COMUNICAZIONE"
    ),
    (
        "37-23",
        "Laurea Magistrale - NANOTECHNOLOGIES FOR ICTs (NANOTECNOLOGIE PER LE ICT)"
    ),
    (
        "37-24",
        "Laurea Magistrale - PHYSICS OF COMPLEX SYSTEMS (FISICA DEI SISTEMI COMPLESSI)"
    ),
    (
        "37-55",
        "Laurea Magistrale - MECHATRONIC ENGINEERING (INGEGNERIA MECCATRONICA)"
    ),
    (
        "38-1",
        "Laurea Magistrale - INGEGNERIA GESTIONALE"
    ),
    (
        "38-3",
        "Laurea Triennale - INGEGNERIA GESTIONALE"
    ),
    -- ("38-5", "Laurea Triennale - INGEGNERIA GESTIONALE"),
    -- ("38-10", "Laurea Magistrale - INGEGNERIA GESTIONALE"),
    (
        "80-1",
        "Laurea Triennale - ARCHITETTURA"
    ),
    -- ("80-2", "Laurea Triennale - ARCHITETTURA"),
    (
        "81-4",
        "Laurea Magistrale - DESIGN SISTEMICO"
    ),
    (
        "81-5",
        "Laurea Magistrale - ARCHITETTURA COSTRUZIONE CITTA'"
    ),
    (
        "81-6",
        "Laurea Triennale - DESIGN E COMUNICAZIONE"
    ),
    (
        "81-83",
        "Laurea Magistrale - DIGITAL SKILLS FOR SUSTAINABLE SOCIETAL TRANSITIONS"
    ),
    (
        "82-4",
        "Laurea Magistrale - ARCHITETTURA PER IL PATRIMONIO"
    ),
    (
        "82-5",
        "Laurea Triennale - PIANIFICAZIONE TERRITORIALE, URBANISTICA E PAESAGGISTICO-AMBIENTALE"
    ),
    (
        "82-6",
        "Laurea Magistrale - ARCHITETTURA PER LA SOSTENIBILITA'"
    );

-- ------------------------------------------------------------
-- ↓ student table ↓
-- ------------------------------------------------------------
INSERT INTO
    student (
        id,
        first_name,
        last_name,
        profile_picture_url,
        degree_id
    )
VALUES
    (
        "320213",
        "Luca",
        "Barbato",
        "https://avatars.githubusercontent.com/u/59212611",
        "37-18"
    ),
    (
        "314796",
        "Daniele",
        "De Rossi",
        "https://avatars.githubusercontent.com/u/114685212",
        "37-18"
    ),
    (
        "318952",
        "Sylvie",
        "Molinatto",
        "https://avatars.githubusercontent.com/u/126864619",
        "37-18"
    );

-- ------------------------------------------------------------
-- ↓ teacher table ↓
-- ------------------------------------------------------------
INSERT INTO
    teacher (
        id,
        first_name,
        last_name,
        role,
        email,
        profile_url,
        profile_picture_url,
        facility_short_name
    )
VALUES
    (
        24514,
        'Francesca',
        'Abastante',
        'Docente',
        'francesca.abastante@polito.it',
        'https://www.dist.polito.it/personale/scheda/(matricola)/024514',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=024514',
        'DIST'
    ),
    (
        3613,
        'Marco',
        'Actis Grande',
        'Docente',
        'marco.actis@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/003613',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003613',
        'DISAT'
    ),
    (
        3614,
        'Valentina',
        'Agostini',
        'Docente',
        'valentina.agostini@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/003614',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003614',
        'DET'
    ),
    (
        1498,
        'Guido',
        'Albertengo',
        'Docente',
        'guido.albertengo@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/001498',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=001498',
        'DET'
    ),
    (
        3013,
        'Arianna',
        'Alfieri',
        'Docente',
        'arianna.alfieri@polito.it',
        'https://www.digep.polito.it/personale/scheda/(matricola)/003013',
        NULL,
        'DIGEP'
    ),
    (
        40463,
        'Alessandro',
        'Aliberti',
        'Docente',
        'alessandro.aliberti@polito.it',
        'https://www.dist.polito.it/personale/scheda/(matricola)/040463',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=040463',
        'DIST'
    ),
    (
        24500,
        'Julia Ginette Nicole',
        'Amici',
        'Docente',
        'julia.amici@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/024500',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=024500',
        'DISAT'
    ),
    (
        15913,
        'Francesco Paolo',
        'Andriulli',
        'Docente',
        'francesco.andriulli@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/015913',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=015913',
        'DET'
    ),
    (
        2024,
        'Dario',
        'Antonelli',
        'Docente',
        'dario.antonelli@polito.it',
        'https://www.digep.polito.it/personale/scheda/(matricola)/002024',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002024',
        'DIGEP'
    ),
    (
        17160,
        'Daniele',
        'Apiletti',
        'Docente',
        'daniele.apiletti@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/017160',
        NULL,
        'DAUIN'
    ),
    (
        23270,
        'Luca',
        'Ardito',
        'Docente',
        'luca.ardito@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/023270',
        NULL,
        'DAUIN'
    ),
    (
        13037,
        'Marco',
        'Armandi',
        'Docente',
        'marco.armandi@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/013037',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=013037',
        'DISAT'
    ),
    (
        44771,
        'Rossella',
        'Arrigo',
        'Docente',
        'rossella.arrigo@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/044771',
        NULL,
        'DISAT'
    ),
    (
        41016,
        'Fiora',
        'Artusio',
        'Docente',
        'fiora.artusio@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/041016',
        NULL,
        'DISAT'
    ),
    (
        2808,
        'Arianna',
        'Astolfi',
        'Docente',
        'arianna.astolfi@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/002808',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002808',
        'DENERG'
    ),
    (
        98692,
        'Francesco',
        'Avallone',
        'Docente',
        'francesco.avallone@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/098692',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=098692',
        'DIMEAS'
    ),
    (
        34463,
        'Alberta',
        'Aversa',
        'Docente',
        'alberta.aversa@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/034463',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=034463',
        'DISAT'
    ),
    (
        39557,
        'Sarah',
        'Azimi',
        'Docente',
        'sarah.azimi@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/039557',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=039557',
        'DAUIN'
    ),
    (
        1899,
        'Marco',
        'Badami',
        'Docente',
        'marco.badami@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/001899',
        NULL,
        'DENERG'
    ),
    (
        19479,
        'Francesco',
        'Baino',
        'Docente',
        'francesco.baino@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/019479',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=019479',
        'DISAT'
    ),
    (
        20436,
        'Cristina',
        'Balagna',
        'Docente',
        'cristina.balagna@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/020436',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=020436',
        'DISAT'
    ),
    (
        2054,
        'Gabriella',
        'Balestra',
        'Docente',
        'gabriella.balestra@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/002054',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002054',
        'DET'
    ),
    (
        20881,
        'Ilaria',
        'Ballarini',
        'Docente',
        'ilaria.ballarini@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/020881',
        NULL,
        'DENERG'
    ),
    (
        3155,
        'Mirko',
        'Baratta',
        'Docente',
        'mirko.baratta@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/003155',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003155',
        'DENERG'
    ),
    (
        38687,
        'Luca',
        'Barbierato',
        'Docente',
        'luca.barbierato@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/038687',
        NULL,
        'DAUIN'
    ),
    (
        12802,
        'Paolo',
        'Bardella',
        'Docente',
        'paolo.bardella@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/012802',
        NULL,
        'DET'
    ),
    (
        3311,
        'Marco',
        'Barla',
        'Docente',
        'marco.barla@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/003311',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003311',
        'DISEG'
    ),
    (
        4039,
        'Michela',
        'Barosio',
        'Docente',
        'michela.barosio@polito.it',
        'https://www.dad.polito.it/personale/scheda/(matricola)/004039',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=004039',
        'DAD'
    ),
    (
        40641,
        'Federico',
        'Barravecchia',
        'Docente',
        'federico.barravecchia@polito.it',
        'https://www.digep.polito.it/personale/scheda/(matricola)/040641',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=040641',
        'DIGEP'
    ),
    (
        60386,
        'Alessandro',
        'Battaglia',
        'Docente',
        'alessandro.battaglia@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/060386',
        NULL,
        'DIATI'
    ),
    (
        31879,
        'Giuseppe',
        'Battiato',
        'Docente',
        'giuseppe.battiato@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/031879',
        NULL,
        'DIMEAS'
    ),
    (
        3307,
        'Manuela',
        'Battipede',
        'Docente',
        'manuela.battipede@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/003307',
        NULL,
        'DIMEAS'
    ),
    (
        2146,
        'Danilo',
        'Bazzanella',
        'Docente',
        'danilo.bazzanella@polito.it',
        'https://www.disma.polito.it/personale/scheda/(matricola)/002146',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002146',
        'DISMA'
    ),
    (
        46334,
        'Elena',
        'Belcore',
        'Docente',
        'elena.belcore@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/046334',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=046334',
        'DIATI'
    ),
    (
        1511,
        'Giovanni',
        'Belingardi',
        'Docente',
        'giovanni.belingardi@formerfaculty.polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/001511',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=001511',
        'DIMEAS'
    ),
    (
        29080,
        'Federico',
        'Bella',
        'Docente',
        'federico.bella@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/029080',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=029080',
        'DISAT'
    ),
    (
        11924,
        'Rossana',
        'Bellopede',
        'Docente',
        'rossana.bellopede@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/011924',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=011924',
        'DIATI'
    ),
    (
        2904,
        'Alfredo',
        'Benso',
        'Docente',
        'alfredo.benso@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/002904',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002904',
        'DAUIN'
    ),
    (
        23819,
        'Luca',
        'Bergamasco',
        'Docente',
        'luca.bergamasco@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/023819',
        NULL,
        'DENERG'
    ),
    (
        4081,
        'Gabriele',
        'Bertagnoli',
        'Docente',
        'gabriele.bertagnoli@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/004081',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=004081',
        'DISEG'
    ),
    (
        39599,
        'Valentina',
        'Bertana',
        'Docente',
        'valentina.bertana@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/039599',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=039599',
        'DISAT'
    ),
    (
        1873,
        'Cristina',
        'Bertani',
        'Docente',
        'cristina.bertani@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/001873',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=001873',
        'DENERG'
    ),
    (
        4135,
        'Francesco',
        'Bertazzi',
        'Docente',
        'francesco.bertazzi@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/004135',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=004135',
        'DET'
    ),
    (
        41266,
        'Antonio Carlo',
        'Bertolino',
        'Docente',
        'antonio.bertolino@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/041266',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=041266',
        'DIMEAS'
    ),
    (
        30842,
        'Tiziano',
        'Bianchi',
        'Docente',
        'tiziano.bianchi@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/030842',
        NULL,
        'DET'
    ),
    (
        2143,
        'Andrea',
        'Bianco',
        'Docente',
        'andrea.bianco@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/002143',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002143',
        'DET'
    ),
    (
        31127,
        'Isabella',
        'Bianco',
        'Docente',
        'isabella.bianco@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/031127',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=031127',
        'DIATI'
    ),
    (
        13543,
        'Enrico',
        'Bibbona',
        'Docente',
        'enrico.bibbona@polito.it',
        'https://www.disma.polito.it/personale/scheda/(matricola)/013543',
        NULL,
        'DISMA'
    ),
    (
        1825,
        'Cristina',
        'Bignardi',
        'Docente',
        'cristina.bignardi@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/001825',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=001825',
        'DIMEAS'
    ),
    (
        38918,
        'Matteo',
        'Bilardo',
        'Docente',
        'matteo.bilardo@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/038918',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=038918',
        'DENERG'
    ),
    (
        13666,
        'Fulvio',
        'Boano',
        'Docente',
        'fulvio.boano@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/013666',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=013666',
        'DIATI'
    ),
    (
        29082,
        'Gianluca',
        'Boccardo',
        'Docente',
        'gianluca.boccardo@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/029082',
        NULL,
        'DISAT'
    ),
    (
        16011,
        'Sergio',
        'Bocchini',
        'Docente',
        'sergio.bocchini@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/016011',
        NULL,
        'DISAT'
    ),
    (
        1906,
        'Silvia',
        'Bodoardo',
        'Docente',
        'silvia.bodoardo@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/001906',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=001906',
        'DISAT'
    ),
    (
        3283,
        'Iustin Radu',
        'Bojoi',
        'Docente',
        'radu.bojoi@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/003283',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003283',
        'DENERG'
    ),
    (
        2351,
        'Ettore Francesco',
        'Bompard',
        'Docente',
        'ettore.bompard@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/002351',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002351',
        'DENERG'
    ),
    (
        2172,
        'Fabrizio',
        'Bonani',
        'Docente',
        'fabrizio.bonani@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/002172',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002172',
        'DET'
    ),
    (
        29862,
        'Federica',
        'Bondioli',
        'Docente',
        'federica.bondioli@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/029862',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=029862',
        'DISAT'
    ),
    (
        13532,
        'Angelo',
        'Bonfitto',
        'Docente',
        'angelo.bonfitto@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/013532',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=013532',
        'DIMEAS'
    ),
    (
        2021,
        'Roberta Maria',
        'Bongiovanni',
        'Docente',
        'roberta.bongiovanni@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/002021',
        NULL,
        'DISAT'
    ),
    (
        26979,
        'Roberto',
        'Bonifetto',
        'Docente',
        'roberto.bonifetto@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/026979',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=026979',
        'DENERG'
    ),
    (
        13572,
        'Michele',
        'Bonnin',
        'Docente',
        'michele.bonnin@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/013572',
        NULL,
        'DET'
    ),
    (
        1872,
        'Romano',
        'Borchiellini',
        'Docente',
        'romano.borchiellini@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/001872',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=001872',
        'DENERG'
    ),
    (
        49848,
        'Luigi',
        'Borzì',
        'Docente',
        'luigi.borzi@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/049848',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=049848',
        'DAUIN'
    ),
    (
        25394,
        'Elisa Francesca',
        'Bosco',
        'Docente a contratto e/o collaboratore didattico',
        'elisa.bosco@polito.it',
        'https://www.dad.polito.it/personale/scheda/(matricola)/025394',
        NULL,
        'DAD'
    ),
    (
        14913,
        'Federico',
        'Bosia',
        'Docente',
        'federico.bosia@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/014913',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=014913',
        'DISAT'
    ),
    (
        2828,
        'Nicola',
        'Bosso',
        'Docente',
        'nicola.bosso@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/002828',
        NULL,
        'DIMEAS'
    ),
    (
        50132,
        'Andrea',
        'Botta',
        'Docente',
        'andrea.botta@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/050132',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=050132',
        'DIMEAS'
    ),
    (
        36638,
        'Lorenzo',
        'Bottaccioli',
        'Docente',
        'lorenzo.bottaccioli@polito.it',
        'https://www.dist.polito.it/personale/scheda/(matricola)/036638',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=036638',
        'DIST'
    ),
    (
        4070,
        'Marta Carla',
        'Bottero',
        'Docente',
        'marta.bottero@polito.it',
        'https://www.dist.polito.it/personale/scheda/(matricola)/004070',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=004070',
        'DIST'
    ),
    (
        3413,
        'Andrea',
        'Bottino',
        'Docente',
        'andrea.bottino@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/003413',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003413',
        'DAUIN'
    ),
    (
        2584,
        'Daniele',
        'Botto',
        'Docente',
        'daniele.botto@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/002584',
        NULL,
        'DIMEAS'
    ),
    (
        37436,
        'Carlo',
        'Boursier Niutta',
        'Docente',
        'carlo.boursier@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/037436',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=037436',
        'DIMEAS'
    ),
    (
        19302,
        'Giovanni',
        'Bracco',
        'Docente',
        'giovanni.bracco@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/019302',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=019302',
        'DIMEAS'
    ),
    (
        1826,
        'Paolo',
        'Brandimarte',
        'Docente',
        'paolo.brandimarte@polito.it',
        'https://www.disma.polito.it/personale/scheda/(matricola)/001826',
        NULL,
        'DISMA'
    ),
    (
        106232,
        'Luca',
        'Brandt',
        'Docente',
        'luca.brandt@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/106232',
        NULL,
        'DIATI'
    ),
    (
        36828,
        'Daniele',
        'Bringhenti',
        'Docente',
        'daniele.bringhenti@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/036828',
        NULL,
        'DAUIN'
    ),
    (
        41311,
        'Fabio',
        'Bruzzone',
        'Docente',
        'fabio.bruzzone@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/041311',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=041311',
        'DIMEAS'
    ),
    (
        17045,
        'Antonio',
        'Buffo',
        'Docente',
        'antonio.buffo@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/017045',
        NULL,
        'DISAT'
    ),
    (
        36284,
        'Alessio',
        'Burrello',
        'Docente',
        'alessio.burrello@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/036284',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=036284',
        'DAUIN'
    ),
    (
        11297,
        'Ilaria',
        'Butera',
        'Docente',
        'ilaria.butera@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/011297',
        NULL,
        'DIATI'
    ),
    (
        59897,
        'Claudia',
        'Caballini',
        'Docente',
        'claudia.caballini@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/059897',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=059897',
        'DIATI'
    ),
    (
        49468,
        'Gioacchino',
        'Cafiero',
        'Docente',
        'gioacchino.cafiero@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/049468',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=049468',
        'DIMEAS'
    ),
    (
        16393,
        'Anna Corinna',
        'Cagliano',
        'Docente',
        'anna.cagliano@polito.it',
        'https://www.digep.polito.it/personale/scheda/(matricola)/016393',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=016393',
        'DIGEP'
    ),
    (
        23058,
        'Luca',
        'Cagliero',
        'Docente',
        'luca.cagliero@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/023058',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=023058',
        'DAUIN'
    ),
    (
        2542,
        'Giuseppe Carlo',
        'Calafiore',
        'Docente',
        'giuseppe.calafiore@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/002542',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002542',
        'DET'
    ),
    (
        18408,
        'Andrea',
        'Calimera',
        'Docente',
        'andrea.calimera@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/018408',
        NULL,
        'DAUIN'
    ),
    (
        94713,
        'Raffaello',
        'Camoriano',
        'Docente',
        'raffaello.camoriano@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/094713',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=094713',
        'DAUIN'
    ),
    (
        31752,
        'Giuseppe',
        'Campo',
        'Docente',
        'giuseppe.campo@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/031752',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=031752',
        'DIATI'
    ),
    (
        11608,
        'Carlo Vincenzo',
        'Camporeale',
        'Docente',
        'carlo.camporeale@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/011608',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=011608',
        'DIATI'
    ),
    (
        39345,
        'Alberto',
        'Cannavò',
        'Docente',
        'alberto.cannavo@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/039345',
        NULL,
        'DAUIN'
    ),
    (
        2177,
        'Aldo',
        'Canova',
        'Docente',
        'aldo.canova@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/002177',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002177',
        'DENERG'
    ),
    (
        19287,
        'Elisa',
        'Capello',
        'Docente',
        'elisa.capello@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/019287',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=019287',
        'DIMEAS'
    ),
    (
        38851,
        'Fabio',
        'Carapellese',
        'Docente',
        'fabio.carapellese@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/038851',
        NULL,
        'DIMEAS'
    ),
    (
        2599,
        'Anna Filomena',
        'Carbone',
        'Docente',
        'anna.carbone@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/002599',
        NULL,
        'DISAT'
    ),
    (
        2899,
        'Andrea',
        'Carena',
        'Docente',
        'andrea.carena@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/002899',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002899',
        'DET'
    ),
    (
        16599,
        'Federico',
        'Carosio',
        'Docente',
        'federico.carosio@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/016599',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=016599',
        'DISAT'
    ),
    (
        2398,
        'Alessio',
        'Carullo',
        'Docente',
        'alessio.carullo@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/002398',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002398',
        'DET'
    ),
    (
        11726,
        'Valentina',
        'Casalegno',
        'Docente',
        'valentina.casalegno@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/011726',
        NULL,
        'DISAT'
    ),
    (
        3752,
        'Claudio Ettore',
        'Casetti',
        'Docente',
        'claudio.casetti@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/003752',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003752',
        'DAUIN'
    ),
    (
        43553,
        'Paolo',
        'Castaldo',
        'Docente',
        'paolo.castaldo@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/043553',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=043553',
        'DISEG'
    ),
    (
        9768,
        'Mario Roberto',
        'Casu',
        'Docente',
        'mario.casu@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/009768',
        NULL,
        'DET'
    ),
    (
        46976,
        'Angioletta Rita',
        'Catalano',
        'Docente',
        'angioletta.catalano@polito.it',
        'https://www.digep.polito.it/personale/scheda/(matricola)/046976',
        NULL,
        'DIGEP'
    ),
    (
        16321,
        'Valentina Alice',
        'Cauda',
        'Docente',
        'valentina.cauda@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/016321',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=016321',
        'DISAT'
    ),
    (
        2535,
        'Andrea',
        'Cavagnino',
        'Docente',
        'andrea.cavagnino@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/002535',
        NULL,
        'DENERG'
    ),
    (
        38367,
        'Marco',
        'Cavana',
        'Docente',
        'marco.cavana@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/038367',
        NULL,
        'DENERG'
    ),
    (
        42737,
        'Pangcheng David',
        'Cen Cheng',
        'Docente',
        'pangcheng.cencheng@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/042737',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=042737',
        'DET'
    ),
    (
        2389,
        'Rosario',
        'Ceravolo',
        'Docente',
        'rosario.ceravolo@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/002389',
        NULL,
        'DISEG'
    ),
    (
        11909,
        'Tania',
        'Cerquitelli',
        'Docente',
        'tania.cerquitelli@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/011909',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=011909',
        'DAUIN'
    ),
    (
        11412,
        'Enrico',
        'Cestino',
        'Docente',
        'enrico.cestino@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/011412',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=011412',
        'DIMEAS'
    ),
    (
        24582,
        'Alessandro',
        'Chiadò',
        'Docente',
        'alessandro.chiado@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/024582',
        NULL,
        'DISAT'
    ),
    (
        2181,
        'Bernardino',
        'Chiaia',
        'Docente',
        'bernardino.chiaia@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/002181',
        NULL,
        'DISEG'
    ),
    (
        2574,
        'Giorgio',
        'Chiandussi',
        'Docente',
        'giorgio.chiandussi@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/002574',
        NULL,
        'DIMEAS'
    ),
    (
        60972,
        'David',
        'Chiaramonti',
        'Docente',
        'david.chiaramonti@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/060972',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=060972',
        'DENERG'
    ),
    (
        3839,
        'Carla Fabiana',
        'Chiasserini',
        'Docente',
        'carla.chiasserini@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/003839',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003839',
        'DET'
    ),
    (
        24188,
        'Eliodoro',
        'Chiavazzo',
        'Docente',
        'eliodoro.chiavazzo@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/024188',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=024188',
        'DENERG'
    ),
    (
        2193,
        'Gianfranco',
        'Chicco',
        'Docente',
        'gianfranco.chicco@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/002193',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002193',
        'DENERG'
    ),
    (
        23085,
        'Giacomo',
        'Chiesa',
        'Docente',
        'giacomo.chiesa@polito.it',
        'https://www.dad.polito.it/personale/scheda/(matricola)/023085',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=023085',
        'DAD'
    ),
    (
        20340,
        'Valeria',
        'Chiono',
        'Docente',
        'valeria.chiono@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/020340',
        NULL,
        'DIMEAS'
    ),
    (
        3201,
        'Silvia Anna',
        'Chiusano',
        'Docente',
        'silvia.chiusano@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/003201',
        NULL,
        'DAUIN'
    ),
    (
        16036,
        'Gianluca',
        'Ciardelli',
        'Docente',
        'gianluca.ciardelli@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/016036',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=016036',
        'DIMEAS'
    ),
    (
        36618,
        'Raffaele',
        'Ciardiello',
        'Docente',
        'raffaele.ciardiello@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/036618',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=036618',
        'DIMEAS'
    ),
    (
        3170,
        'Giancarlo',
        'Cicero',
        'Docente',
        'giancarlo.cicero@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/003170',
        NULL,
        'DISAT'
    ),
    (
        22981,
        'Gian Paolo',
        'Cimellaro',
        'Docente',
        'gianpaolo.cimellaro@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/022981',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=022981',
        'DISEG'
    ),
    (
        29797,
        'Alessandro',
        'Ciocia',
        'Docente',
        'alessandro.ciocia@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/029797',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=029797',
        'DENERG'
    ),
    (
        35720,
        'Marco',
        'Civera',
        'Docente',
        'marco.civera@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/035720',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=035720',
        'DISEG'
    ),
    (
        3366,
        'Pierluigi',
        'Claps',
        'Docente',
        'pierluigi.claps@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/003366',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003366',
        'DIATI'
    ),
    (
        31299,
        'Pietro',
        'Colella',
        'Docente',
        'pietro.colella@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/031299',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=031299',
        'DENERG'
    ),
    (
        41312,
        'Elisabetta',
        'Colucci',
        'Docente',
        'elisabetta.colucci@polito.it',
        'https://www.dad.polito.it/personale/scheda/(matricola)/041312',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=041312',
        'DAD'
    ),
    (
        18780,
        'Giovanna',
        'Colucci',
        'Docente',
        'giovanna.colucci@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/018780',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=018780',
        'DISAT'
    ),
    (
        38485,
        'Riccardo',
        'Coppola',
        'Docente',
        'riccardo.coppola@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/038485',
        NULL,
        'DAUIN'
    ),
    (
        12868,
        'Simone',
        'Corbellini',
        'Docente',
        'simone.corbellini@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/012868',
        NULL,
        'DET'
    ),
    (
        3229,
        'Sabrina',
        'Corpino',
        'Docente',
        'sabrina.corpino@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/003229',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003229',
        'DIMEAS'
    ),
    (
        16303,
        'Mauro',
        'Corrado',
        'Docente',
        'mauro.corrado@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/016303',
        NULL,
        'DISEG'
    ),
    (
        1996,
        'Vincenzo',
        'Corrado',
        'Docente',
        'vincenzo.corrado@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/001996',
        NULL,
        'DENERG'
    ),
    (
        3740,
        'Cristina',
        'Coscia',
        'Docente',
        'cristina.coscia@polito.it',
        'https://www.dad.polito.it/personale/scheda/(matricola)/003740',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003740',
        'DAD'
    ),
    (
        23003,
        'Renato Maria',
        'Cosentini',
        'Docente',
        'renato.cosentini@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/023003',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=023003',
        'DISEG'
    ),
    (
        33555,
        'Elisa',
        'Costamagna',
        'Docente',
        'elisa.costamagna@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/033555',
        NULL,
        'DIATI'
    ),
    (
        2629,
        'Giovanni Antonio',
        'Costanzo',
        'Docente',
        'giovanni.costanzo@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/002629',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002629',
        'DET'
    ),
    (
        4007,
        'Paolo Stefano',
        'Crovetti',
        'Docente',
        'paolo.crovetti@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/004007',
        NULL,
        'DET'
    ),
    (
        1831,
        'Francesca Maria',
        'Curà',
        'Docente',
        'francesca.cura@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/001831',
        NULL,
        'DIMEAS'
    ),
    (
        3641,
        'Fabrizio',
        'Dabbene',
        'Docente a contratto e/o collaboratore didattico',
        'fabrizio.dabbene@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/003641',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003641',
        'DAUIN'
    ),
    (
        3643,
        'Dario',
        'Daghero',
        'Docente',
        'dario.daghero@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/003643',
        NULL,
        'DISAT'
    ),
    (
        2923,
        'Bruno',
        'Dalla Chiara',
        'Docente',
        'bruno.dallachiara@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/002923',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002923',
        'DIATI'
    ),
    (
        13692,
        'Matteo Davide Lorenzo',
        'Dalla Vedova',
        'Docente',
        'matteo.dallavedova@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/013692',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=013692',
        'DIMEAS'
    ),
    (
        38997,
        'Carlo',
        'De Benedictis',
        'Docente',
        'carlo.debenedictis@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/038997',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=038997',
        'DIMEAS'
    ),
    (
        27419,
        'Valerio',
        'De Biagi',
        'Docente',
        'valerio.debiagi@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/027419',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=027419',
        'DISEG'
    ),
    (
        38258,
        'Henrique',
        'De Carvalho Pinheiro',
        'Docente',
        'henrique.decarvalho@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/038258',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=038258',
        'DIMEAS'
    ),
    (
        32322,
        'Stefano',
        'De La Pierre Des Ambrois',
        'Docente',
        'stefano.delapierre@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/032322',
        NULL,
        'DISAT'
    ),
    (
        11676,
        'Manuela',
        'De Maddis',
        'Docente',
        'manuela.demaddis@polito.it',
        'https://www.digep.polito.it/personale/scheda/(matricola)/011676',
        NULL,
        'DIGEP'
    ),
    (
        32259,
        'Andrea',
        'De Martin',
        'Docente',
        'andrea.demartin@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/032259',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=032259',
        'DIMEAS'
    ),
    (
        18413,
        'Giorgio',
        'De Pasquale',
        'Docente',
        'giorgio.depasquale@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/018413',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=018413',
        'DIMEAS'
    ),
    (
        25734,
        'Luigi',
        'De Russis',
        'Docente',
        'luigi.derussis@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/025734',
        NULL,
        'DAUIN'
    ),
    (
        49588,
        'Corrado',
        'De Sio',
        'Docente',
        'corrado.desio@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/049588',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=049588',
        'DAUIN'
    ),
    (
        3990,
        'Francesco Paolo',
        'Deflorio',
        'Docente',
        'francesco.deflorio@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/003990',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003990',
        'DIATI'
    ),
    (
        29274,
        'Matteo',
        'Del Giudice',
        'Docente',
        'matteo.delgiudice@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/029274',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=029274',
        'DISEG'
    ),
    (
        4171,
        'Marcello Edoardo',
        'Delitala',
        'Docente',
        'marcello.delitala@polito.it',
        'https://www.disma.polito.it/personale/scheda/(matricola)/004171',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=004171',
        'DISMA'
    ),
    (
        46539,
        'Francesco',
        'Della Santa',
        'Docente',
        'francesco.dellasanta@polito.it',
        'https://www.disma.polito.it/personale/scheda/(matricola)/046539',
        NULL,
        'DISMA'
    ),
    (
        1958,
        'Cristiana',
        'Delprete',
        'Docente',
        'cristiana.delprete@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/001958',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=001958',
        'DIMEAS'
    ),
    (
        2371,
        'Danilo',
        'Demarchi',
        'Docente',
        'danilo.demarchi@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/002371',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002371',
        'DET'
    ),
    (
        2818,
        'Micaela',
        'Demichela',
        'Docente',
        'micaela.demichela@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/002818',
        NULL,
        'DISAT'
    ),
    (
        37288,
        'Francesca',
        'Demichelis',
        'Docente',
        'francesca.demichelis@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/037288',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=037288',
        'DISAT'
    ),
    (
        11813,
        'Fabio Alessandro',
        'Deorsola',
        'Docente',
        'fabio.deorsola@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/011813',
        NULL,
        'DISAT'
    ),
    (
        17632,
        'Marco Agostino',
        'Deriu',
        'Docente',
        'marco.deriu@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/017632',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=017632',
        'DIMEAS'
    ),
    (
        16710,
        'Emiliano',
        'Descrovi',
        'Docente',
        'emiliano.descrovi@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/016710',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=016710',
        'DISAT'
    ),
    (
        3272,
        'Stefano',
        'Di Carlo',
        'Docente',
        'stefano.dicarlo@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/003272',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003272',
        'DAUIN'
    ),
    (
        19491,
        'Santa',
        'Di Cataldo',
        'Docente',
        'santa.dicataldo@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/019491',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=019491',
        'DAUIN'
    ),
    (
        51055,
        'Enzo Mario',
        'Di Fabrizio',
        'Docente',
        'enzo.difabrizio@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/051055',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=051055',
        'DISAT'
    ),
    (
        32925,
        'Vincenzo',
        'Di Pietra',
        'Docente',
        'vincenzo.dipietra@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/032925',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=032925',
        'DIATI'
    ),
    (
        13461,
        'Antonio Josè',
        'Di Scala',
        'Docente',
        'antonio.discala@polito.it',
        'https://www.disma.polito.it/personale/scheda/(matricola)/013461',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=013461',
        'DISMA'
    ),
    (
        43554,
        'Fabio',
        'Di Trapani',
        'Docente',
        'fabio.ditrapani@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/043554',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=043554',
        'DISEG'
    ),
    (
        3206,
        'Marco',
        'Diana',
        'Docente',
        'marco.diana@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/003206',
        NULL,
        'DIATI'
    ),
    (
        38991,
        'Luca',
        'Dimauro',
        'Docente',
        'luca.dimauro@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/038991',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=038991',
        'DIMEAS'
    ),
    (
        3851,
        'Fabrizio',
        'Dolcini',
        'Docente',
        'fabrizio.dolcini@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/003851',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003851',
        'DISAT'
    ),
    (
        43280,
        'Marco',
        'Domaneschi',
        'Docente',
        'marco.domaneschi@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/043280',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=043280',
        'DISEG'
    ),
    (
        56800,
        'Serena',
        'Esposito',
        'Docente',
        'serena_esposito@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/056800',
        NULL,
        'DISAT'
    ),
    (
        2562,
        'Gabriella',
        'Eula',
        'Docente',
        'gabriella.eula@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/002562',
        NULL,
        'DIMEAS'
    ),
    (
        32649,
        'Edoardo',
        'Fadda',
        'Docente',
        'edoardo.fadda@polito.it',
        'https://www.disma.polito.it/personale/scheda/(matricola)/032649',
        NULL,
        'DISMA'
    ),
    (
        68540,
        'Nicolas Ezequiel',
        'Faedo',
        'Docente',
        'nicolas.faedo@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/068540',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=068540',
        'DIMEAS'
    ),
    (
        64370,
        'Devid',
        'Falliano',
        'Docente',
        'devid.falliano@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/064370',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=064370',
        'DISEG'
    ),
    (
        39181,
        'Gabriele',
        'Fambri',
        'Docente',
        'gabriele.fambri@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/039181',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=039181',
        'DENERG'
    ),
    (
        26208,
        'Matteo',
        'Fasano',
        'Docente',
        'matteo.fasano@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/026208',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=026208',
        'DENERG'
    ),
    (
        26986,
        'Fabio',
        'Favoino',
        'Docente',
        'fabio.favoino@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/026986',
        NULL,
        'DENERG'
    ),
    (
        26717,
        'Valeria',
        'Federighi',
        'Docente',
        'valeria.federighi@polito.it',
        'https://www.dad.polito.it/personale/scheda/(matricola)/026717',
        NULL,
        'DAD'
    ),
    (
        38425,
        'Sofia',
        'Fellini',
        'Docente',
        'sofia.fellini@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/038425',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=038425',
        'DIATI'
    ),
    (
        28188,
        'Maria',
        'Ferrara',
        'Docente',
        'maria.ferrara@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/028188',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=028188',
        'DENERG'
    ),
    (
        1523,
        'Carlo',
        'Ferraresi',
        'Docente a contratto e/o collaboratore didattico',
        'carlo.ferraresi@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/001523',
        NULL,
        'DIMEAS'
    ),
    (
        41351,
        'Simone',
        'Ferrari',
        'Docente',
        'simone.ferrari@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/041351',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=041351',
        'DENERG'
    ),
    (
        2157,
        'Luca',
        'Ferraris',
        'Docente',
        'luca.ferraris@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/002157',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002157',
        'DENERG'
    ),
    (
        2025,
        'Monica',
        'Ferraris',
        'Docente',
        'monica.ferraris@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/002025',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002025',
        'DISAT'
    ),
    (
        22269,
        'Renato',
        'Ferrero',
        'Docente',
        'renato.ferrero@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/022269',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=022269',
        'DAUIN'
    ),
    (
        3464,
        'Sergio',
        'Ferrero',
        'Docente',
        'sergio.ferrero@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/003464',
        NULL,
        'DISAT'
    ),
    (
        38439,
        'Carlo Giovanni',
        'Ferro',
        'Docente',
        'carlo.ferro@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/038439',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=038439',
        'DIMEAS'
    ),
    (
        2103,
        'Giuseppe Andrea',
        'Ferro',
        'Docente',
        'giuseppe.ferro@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/002103',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002103',
        'DISEG'
    ),
    (
        29097,
        'Matteo',
        'Filippi',
        'Docente',
        'matteo.filippi@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/029097',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=029097',
        'DIMEAS'
    ),
    (
        3061,
        'Debora',
        'Fino',
        'Docente',
        'debora.fino@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/003061',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003061',
        'DISAT'
    ),
    (
        3184,
        'Silvia',
        'Fiore',
        'Docente',
        'silvia.fiore@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/003184',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003184',
        'DIATI'
    ),
    (
        14207,
        'Alessandro',
        'Fiori',
        'Docente a contratto e/o collaboratore didattico',
        'alessandro.fiori@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/014207',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=014207',
        'DAUIN'
    ),
    (
        17980,
        'Marco',
        'Fioriti',
        'Docente',
        'marco.fioriti@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/017980',
        NULL,
        'DIMEAS'
    ),
    (
        12851,
        'Christian Maria',
        'Firrone',
        'Docente',
        'christian.firrone@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/012851',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=012851',
        'DIMEAS'
    ),
    (
        4077,
        'Davide',
        'Fissore',
        'Docente',
        'davide.fissore@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/004077',
        NULL,
        'DISAT'
    ),
    (
        29203,
        'Marco',
        'Fontana',
        'Docente',
        'marco.fontana@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/029203',
        NULL,
        'DISAT'
    ),
    (
        17439,
        'Sophie',
        'Fosson',
        'Docente',
        'sophie.fosson@polito.it',
        'https://www.dauin.polito.it/personale/scheda/(matricola)/017439',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=017439',
        'DAUIN'
    ),
    (
        4176,
        'Sebastiano',
        'Foti',
        'Docente',
        'sebastiano.foti@polito.it',
        'https://www.diseg.polito.it/personale/scheda/(matricola)/004176',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=004176',
        'DISEG'
    ),
    (
        3656,
        'Alberto',
        'Frache',
        'Docente',
        'alberto.frache@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/003656',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003656',
        'DISAT'
    ),
    (
        2580,
        'Carlotta',
        'Francia',
        'Docente',
        'carlotta.francia@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/002580',
        NULL,
        'DISAT'
    ),
    (
        2825,
        'Walter',
        'Franco',
        'Docente',
        'walter.franco@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/002825',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002825',
        'DIMEAS'
    ),
    (
        17408,
        'Francesca',
        'Frascella',
        'Docente',
        'francesca.frascella@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/017408',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=017408',
        'DISAT'
    ),
    (
        33627,
        'Antonio',
        'Froio',
        'Docente',
        'antonio.froio@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/033627',
        NULL,
        'DENERG'
    ),
    (
        1910,
        'Giacomo',
        'Frulla',
        'Docente',
        'giacomo.frulla@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/001910',
        NULL,
        'DIMEAS'
    ),
    (
        32281,
        'Manuela',
        'Galati',
        'Docente',
        'manuela.galati@polito.it',
        'https://www.digep.polito.it/personale/scheda/(matricola)/032281',
        NULL,
        'DIGEP'
    ),
    (
        3331,
        'Maurizio',
        'Galetto',
        'Docente',
        'maurizio.galetto@polito.it',
        'https://www.digep.polito.it/personale/scheda/(matricola)/003331',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003331',
        'DIGEP'
    ),
    (
        16313,
        'Enrico',
        'Galvagno',
        'Docente',
        'enrico.galvagno@polito.it',
        'https://www.dimeas.polito.it/personale/scheda/(matricola)/016313',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=016313',
        'DIMEAS'
    ),
    (
        2020,
        'Andrea Antonio',
        'Gamba',
        'Docente',
        'andrea.gamba@polito.it',
        'https://www.disat.polito.it/personale/scheda/(matricola)/002020',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=002020',
        'DISAT'
    ),
    (
        29869,
        'Marta',
        'Gandiglio',
        'Docente',
        'marta.gandiglio@polito.it',
        'https://www.denerg.polito.it/personale/scheda/(matricola)/029869',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=029869',
        'DENERG'
    ),
    (
        18120,
        'Daniele',
        'Ganora',
        'Docente',
        'daniele.ganora@polito.it',
        'https://www.diati.polito.it/personale/scheda/(matricola)/018120',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=018120',
        'DIATI'
    ),
    (
        98620,
        'Andrea',
        'Marchisio',
        'Dottorando',
        'andrea_marchisio@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/098620',
        NULL,
        'DET'
    ),
    (
        3019,
        'Marco',
        'Torchiano',
        'Docente',
        'marco.torchiano@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/003019',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=003019',
        'DAUIN'
    ),
    (
        16873,
        'Antonio',
        'Vetrò',
        'Docente',
        'antonio.vetro@polito.it',
        'https://www.det.polito.it/personale/scheda/(matricola)/016873',
        'https://www.swas.polito.it/_library/image_pub.asp?matricola=016873',
        'DAUIN'
    );

-- ------------------------------------------------------------
-- ↓ keyword table ↓
-- ------------------------------------------------------------
INSERT INTO
    keyword (id, keyword, keyword_en)
VALUES
    -- ------------------------------------------------------------
    -- ↓ thesis_proposal table ↓
    -- ------------------------------------------------------------
INSERT INTO
    thesis_proposal (
        id,
        type,
        type_en,
        topic,
        topic_en,
        description,
        description_en,
        link,
        required_skills,
        required_skills_en,
        additional_notes,
        additional_notes_en,
        external_cosupervisors,
        creation_date,
        expiration_date,
        is_internal,
        is_abroad,
        area,
        level,
        attachment_url
    )
VALUES
    (
        13169,
        "Ricerca",
        "Research",
        "Studio esplorativo delle soluzioni AI-based per la generazione del codice",
        "An exploration of the solutions for AI-based code generation",
        "La tesi comporta una completa esplorazione delle soluzioni attuali nel dominio. L'obiettivo è valutare le metodologie esistenti, le tecnologie e i framework rilevanti per il contesto di ricerca. Questa analisi preliminare sarà condotta in modo sistematico applicando le linee guida di Kitchenham per la conduzione di Revisioni Bibliografiche Sistematiche nel campo della Ricerca in Ingegneria del Software. La revisione bibliografica sistematica terrà conto anche delle fonti di letteratura grigia (cioè, fonti non sottoposte a revisione tra pari disponibili su varie fonti internet) per far fronte alla grande novità del campo della ricerca sull'IA generativa. La valutazione sistematica dello stato dell'arte sarà integrata con la conduzione di interviste aperte e strutturate con professionisti e sviluppatori per comprendere le loro principali esigenze e pratiche più comuni.",
        "The thesis involves a comprehensive exploration of current solutions in the domain. The objective is to evaluate existing methodologies, technologies, and frameworks relevant to the research context. This preliminary analysis will be conducted in a systematic way by applying Kitchenham's guidelines for the conduction of Systematic Literature Reviews in the Software Engineering research field. The systematic literature review will also consider grey-literature sources (i.e., non-peer reviewed sources available on various internet sources) to cope with the high novelty of the generative AI research field. The systematic evaluation of the state of the art will be complemented with the conduction of open and structured interviews with practitioners and developers to understand their main needs and most common practices.",
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        "2023-12-07",
        "2024-12-07",
        1,
        0,
        'Ingegneria',
        '2',
        NULL
    );

-- ------------------------------------------------------------
-- ↓ thesis_proposal_degree table ↓
-- ------------------------------------------------------------
INSERT INTO
    thesis_proposal_degree (thesis_proposal_id, degree_id)
VALUES
    (13169, "37-18");

-- ------------------------------------------------------------
-- ↓ thesis_proposal_keyword table ↓
-- ------------------------------------------------------------
INSERT INTO
    thesis_proposal_keyword (thesis_proposal_id, keyword_id)
VALUES
    ();

-- ------------------------------------------------------------
-- ↓ thesis_proposal_supervisor_cosupervisor table ↓
-- ------------------------------------------------------------
INSERT INTO
    thesis_proposal_supervisor_cosupervisor (thesis_proposal_id, teacher_id, is_supervisor)
VALUES
    (13169, 38485, 1);